# Site
name: 'Blog'
description: 'Review de Camaras y lentes de todas las marcas compatible con camaras Sony y Canon'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blog'
disqus: 'demowebsite'
email: 'davidcon1camara@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           David
      site:           https://davidcon1camara.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hola, soy DAvid Ortega M. creador de este blog para que puedas disfrutar de noticias y reviews independientes"
      email:          davidcon1camara@gmail.com
      twitter:        https://twitter.com/israeldavid76

    jane:
      name:           Israel
      site:           https://israel.com
      avatar:         /assets/images/avatar_2.png
      bio:            "Blogger, me gusta explorar nuevas ideas, me gusta Batman"
      email:          israeldavid@gmail.com
      twitter:        https://twitter.com/israeldavid76
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
